import { BusinessTypeName } from '../enum/business-type.enum';
import { FeatureName } from '../enum/feature-types.enum';
import { OrientationName } from '../enum/orientation-types.enum';
import { PaymentMethodName } from '../enum/payment-method-types.enum';
import { Experience } from './Experience';
import { MenuCategory } from './MenuCategory';
import { OpenHour } from './OpenHour';
import { Product } from './Product';
import { Link } from './Link';
import { PrivateEvent } from './PrivateEvent';
import { PublicEvent } from './PublicEvent';
import { Offer } from './Offer';
import { BadgeTitle } from '../enum/badge-types.enum';

export interface BusinessResponse {
    business_id: string;
    business_owner_id: string;
    name: string;
    logo: string;
    business_type: string;
    street: string;
    building_number: string;
    country: string;
    region: string;
    phone_number: string;
    business_email: string;
    payment_methods: Array<string>;
    menu_categories: Array<string>;
    products: Array<string>;
    links: Array<string>;
    consumer_reviews: Array<string>;
    private_events: Array<string>;
    public_events: Array<string>;
    features: Array<string>;
    open_hours: Array<string>;
    food_experience: Array<string>;
    place_experience: Array<string>;
    drink_experience: Array<string>;
    delivery_experience: Array<string>;
    dress_code: Array<string>;
    dress_code_description: string;
    business_reservations: Array<string>;
    reservation_required: string;
    continuous_service: string;
    followers_count: string;
    is_published: string;
    is_reservation_system_active: string;
    badges: Array<string>;
    offers: Array<string>;
    average_per_person: string;
    orientations: Array<string>;
    creation_date: string;
}
export interface Business {
    businessId: string;
    shortId: string;
    businessOwnerId: string;
    name: string;
    logo: string;
    businessType: BusinessTypeName;
    street: string;
    buildingNumber: string;
    country: string;
    region: string;
    phoneNumber: string;
    businessEmail: string;
    paymentMethods: Array<PaymentMethodName>;
    menuCategories: Array<MenuCategory>;
    products: Array<Product>;
    links: Array<Link>;
    consumerReviews: Array<string>;
    private_events: Array<PrivateEvent>;
    public_events: Array<PublicEvent>;
    features: Array<FeatureName>;
    openHours: Array<OpenHour>;
    foodExperience: Experience;
    placeExperience: Experience;
    drinkExperience: Experience;
    deliveryExperience: Experience;
    dressCode: Array<string>;
    dressCodeDescription: string;
    businessReservations: Array<string>;
    reservationRequired: boolean;
    continuousService: boolean;
    followersCount: number;
    isPublished: boolean;
    isReservationSystemActive: boolean;
    badges: Array<BadgeTitle>;
    offers: Array<Offer>;
    averagePerPerson: number;
    orientations: Array<OrientationName>;
    creationDate: string;
}
