export enum BadgeTitle {
    HALAL = 'HALAL',
    VEGAN = 'VEGAN',
    VEGITARIAN = 'VEGITARIAN',
    KOSHER = 'KOSHER',
    PESCATARIAN = 'PESCATARIAN',
    MICHELIN = 'MICHELIN',
    UNDEFINED_BADGE = 'UNDEFINED_BADGE',
}
