export enum DressCode {
    CASUAL = 'CASUAL',
    BUSINESS_CASUAL = 'BUSINESS_CASUAL',
    SMART_CASUAL = 'SMART_CASUAL',
    FORMAL = 'FORMAL',
    SEMI_FORMAL = 'SEMI_FORMAL',
    SWIMMING_SUIT = 'SWIMMING_SUIT',
    NO_DRESSCODE = 'NO_DRESSCODE',
    UNDEFINED_DRESS_CODE = 'UNDEFINED_DRESS_CODE',
}
