export enum OpenHourTypes {
    FIRST_PERIOD_OPEN = 'FIRST_PERIOD_OPEN',
    FIRST_PERIOD_CLOSE = 'FIRST_PERIOD_CLOSE',
    SECOND_PERIOD_OPEN = 'SECOND_PERIOD_OPEN',
    SECOND_PERIOD_CLOSE = 'SECOND_PERIOD_CLOSE',
}
