export enum PaymentMethodName {
    CASH = 'CASH',
    CREDIT_CARD = 'CREDIT_CARD',
    APPLE_PAY = 'APPLE_PAY',
    VISA = 'VISA',
    AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
    MASTER_CARD = 'MASTER_CARD',
    ALL = 'ALL',
    UNDEFINED_METHOD = 'UNDEFINED_METHOD',
}
