export enum PrivateEventsTypes {
    BIRTHDAY_PARTY = 'BIRTHDAY_PARTY',
    WORK_EVENTS = 'WORK_EVENTS',
    BABY_SHOWER = 'BABY_SHOWER',
    BAR_MITZVAH = 'BAR_MITZVAH',
    BABY_REVEALING_PARTY = 'BABY_REVEALING_PARTY',
    GRADUATION_PARTIES = 'GRADUATION_PARTIES',
}
